attempt to use newer vvl sdk

diff --git a/.github/workflows/cmake-validate-vulkan-linux.yml b/.github/workflows/cmake-validate-vulkan-linux.yml
--- a/.github/workflows/cmake-validate-vulkan-linux.yml
+++ b/.github/workflows/cmake-validate-vulkan-linux.yml
@@ -34,14 +34,20 @@ jobs:
             lcov \
             libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libxkbcommon-dev 
 
-      - name: Prepare Vulkan SDK
-        uses: humbletim/setup-vulkan-sdk@v1.2.1
-        with:
-            vulkan-query-version: latest
-            vulkan-components: Vulkan-Headers, Vulkan-Loader
-            vulkan-use-cache: true
-      - name: Install Vulkan Validation Layers
-        run: sudo apt-get update && sudo apt-get install -y vulkan-validationlayers
+      - name: Download and extract Vulkan SDK
+        env:
+          VULKAN_SDK_VERSION: 1.4.321.1
+        run: |
+          curl -LO https://sdk.lunarg.com/sdk/download/${VULKAN_SDK_VERSION}/linux/vulkan-sdk-linux-x86_64-${VULKAN_SDK_VERSION}.tar.xz
+          tar -xf vulkan-sdk-linux-x86_64-${VULKAN_SDK_VERSION}.tar.xz -C $HOME
+          echo "VULKAN_SDK=$HOME/${VULKAN_SDK_VERSION}/x86_64" >> $GITHUB_ENV
+          echo "source $HOME/${VULKAN_SDK_VERSION}/x86_64/setup-env.sh" >> $GITHUB_ENV
+
+      - name: Source Vulkan SDK environment
+        run: |
+          source $VULKAN_SDK/setup-env.sh
+          vulkaninfo | grep VK_LAYER_KHRONOS_validation || echo "Validation layer not found!"
+          
       - name: Install Vulkan Mesa Drivers
         run: sudo apt install mesa-vulkan-drivers
         
